

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: pass-backend-test
    env_file:
      - ../.env
    environment:
      - DEBUG=True  # 本地调试模式
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ../logs:/app/logs
      - ../db.sqlite3:/app/db.sqlite3
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        - VITE_API_BASE_URL=http://backend:8000/api
    container_name: pass-frontend-test
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_static:
  backend_media: