version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: pass-backend
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me}
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ../logs:/app/logs
      - ../db.sqlite3:/app/db.sqlite3
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: pass-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_static:
  backend_media: