# Generated by Django 5.0.1 on 2025-06-23 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_type',
            field=models.CharField(choices=[('record', '记录'), ('requirement', '需求'), ('task', '任务'), ('issue', '故障')], default='record', help_text='todo类型', max_length=20, verbose_name='类型'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['todo_type'], name='todos_todo_todo_ty_430ce7_idx'),
        ),
    ]
