# Generated by Django 5.2.3 on 2025-07-03 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='parent_todo_id',
            field=models.PositiveIntegerField(blank=True, help_text='父级任务的ID，用于建立任务层级关系', null=True, verbose_name='父任务ID'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['parent_todo_id'], name='todos_todo_parent__7b05ad_idx'),
        ),
    ]
