# Generated by Django 5.2.3 on 2025-07-03 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_parent_todo_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': '待办事项', 'verbose_name_plural': '待办事项'},
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('critical', '严重'), ('urgent', '紧急'), ('normal', '一般'), ('none', '无')], default='none', help_text='任务优先级', max_length=20, verbose_name='优先级'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['priority'], name='todos_todo_priorit_93f987_idx'),
        ),
    ]
