# Generated by Django 5.2.3 on 2025-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_options_todo_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低'), ('none', '无')], default='none', help_text='任务优先级', max_length=20, verbose_name='优先级'),
        ),
    ]
