# Generated by Django 5.2.3 on 2025-07-07 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_update_priority_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', '待阅'), ('archived', '归档'), ('pending_evaluation', '待评估'), ('decomposed', '已拆解'), ('rejected', '已拒绝'), ('todo', '待办'), ('on_hold', '搁置'), ('cancelled', '取消'), ('completed', '完成'), ('reported', '报告'), ('reproduced', '复现'), ('fixing', '修复'), ('resolved', '解决'), ('closed', '关闭')], default='pending', help_text='任务状态', max_length=30, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['status'], name='todos_todo_status_9f7c48_idx'),
        ),
    ]
