# Generated by Django 5.2.3 on 2025-07-08 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_todo_status_todo_todos_todo_status_9f7c48_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '待阅'), ('archived', '归档'), ('pending_evaluation', '待评估'), ('decomposed', '已拆解'), ('rejected', '已拒绝'), ('todo', '待办'), ('on_hold', '搁置'), ('cancelled', '取消'), ('completed', '完成'), ('reported', '报告'), ('reproduced', '复现'), ('fixing', '修复'), ('resolved', '解决'), ('closed', '关闭')], help_text='任务状态', max_length=30, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='QuickTaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='快捷任务名称，将作为按钮显示文字', max_length=50, verbose_name='配置名称')),
                ('title', models.CharField(help_text='任务标题模板，支持变量如{date}, {time}, {user}', max_length=200, verbose_name='任务标题模板')),
                ('description', models.TextField(blank=True, help_text='任务描述模板，支持变量替换', verbose_name='任务描述模板')),
                ('todo_type', models.CharField(choices=[('record', '记录'), ('requirement', '需求'), ('task', '任务'), ('issue', '故障')], default='record', help_text='快捷任务的类型', max_length=20, verbose_name='任务类型')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低'), ('none', '无')], default='medium', help_text='快捷任务的优先级', max_length=20, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, help_text='是否在舰桥页面显示此快捷按钮', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(help_text='配置的创建者', on_delete=django.db.models.deletion.CASCADE, related_name='quick_task_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '快捷任务配置',
                'verbose_name_plural': '快捷任务配置',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='todos_quick_created_cc10c1_idx'), models.Index(fields=['is_active'], name='todos_quick_is_acti_373a78_idx'), models.Index(fields=['todo_type'], name='todos_quick_todo_ty_7c55b6_idx')],
                'unique_together': {('created_by', 'name')},
            },
        ),
    ]
