# Generated by Django 5.2.3 on 2025-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='persona',
            field=models.CharField(choices=[('DefaultAssistant', '高效机器'), ('LifeAssistant', '知心姐姐'), ('MilitaryAssistant', '铁血军官'), ('DevelopmentAssistant', '睿智博士')], default='DefaultAssistant', help_text='仅对AI助手消息有效', max_length=20, verbose_name='AI人格'),
        ),
    ]
