# Generated by Django 5.2.3 on 2025-07-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='referenced_todos',
            field=models.JSONField(blank=True, default=list, help_text='存储引用的todo列表，格式为[{id, title, type, priority, description}]', verbose_name='引用的Todo'),
        ),
    ]
